solar: solar.c
	gcc solar.c -o solar -lopengl32 -lglu32 -lfreeglut

solar2: solar2.c
	gcc solar2.c -o solar2 -lopengl32 -lglu32 -lfreeglut

code: code.c
	gcc code.c -o code -lopengl32 -lglu32 -lfreeglut

.PHONY: clear

clear:
	rm *.o