linkedlist: linkedlist.c
	gcc -c linkedlist.c

lltest: linkedlist lltest.c
	gcc -c lltest.c
	gcc linkedlist.o lltest.o -o lltest


seqlist: seqlist.c
	gcc -c seqlist.c

sltest: seqlist sltest.c
	gcc -c sltest.c
	gcc seqlist.o sltest.o -o sltest


doublylinkedlist: doublylinkedlist.c
	gcc -c doublylinkedlist.c

dlltest: doublylinkedlist dlltest.c
	gcc -c dlltest.c
	gcc doublylinkedlist.o dlltest.o -o dlltest